/* -------------------------------------------------------------------
   program name:  

 statistical computation of the log files generated by all other
 programs

   parameters:  filename Inxtances
                filename exact solutions
	   filename asymmetric
	   filename symmetric
	   filename strong symmetric
	   filename Long Run
	   filename Linear
	   Output filename Statistics
	   Output filename Results

------------------------------------------------------------------- */
#include <float.h>

#define MAXSTR 100     /* maximum number of strings in an instance */
#define MAXLEN 1000    /* maximum length of a string */
#define MAXALPHABET 20 /* maximum size of the alphabet */
#define MAXINT 65535
#define MAXSEQ_PD 4
#define MAXLENGTH_PD 100

#define MAX_INSTANCES 1000


#define LONG 1
#define SHORT 0

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
char min_alphabet,max_alphabet;
 char alphabet[MAXALPHABET];

int Truelen(char *seq)
{
int i;
for(i=0;seq[i] <= max_alphabet && seq[i] >= min_alphabet &&	i<MAXLEN; i++)
    {}
return i;
}


/* ------------------------------------------------------------
   Compute the number of blocks of a string
------------------------------------------------------------ */
int num_blocks(char *s)
{
  int i,j=1;
  int k;

  k=Truelen(s);
  for (i=1;i<k;i++)
    if (s[i]!=s[i-1])
      j++;

  return(j);
}


void get_alphabet(char distrib[MAXLEN], int size)
{
    int i;
    char symbol, temp[MAXLEN];
    FILE *disfil;
    if ((disfil=fopen(distrib,"r"))==NULL) 
 	{
 	    printf("File <%s> cannot be accessed\n",distrib); 
 	    exit(5); 
	}
    for(i=1;i<=size; i++)
	{
	    fscanf(disfil,"%c%s\n", &symbol , temp);
	    alphabet[i-1]=symbol;
	}
 for(i=1,max_alphabet=alphabet[0],min_alphabet=alphabet[0];i<size; i++)
	    if (alphabet[i]>max_alphabet)
		max_alphabet=alphabet[i];
	    else 
		if(alphabet[i]<min_alphabet)
		    min_alphabet=alphabet[i];
 fclose(disfil);
}


/* 0=Exact 1= Asymm 2=Symm, 3=StrongSymm 4=LongRun 5=Linear */
int main(argc,argv)
    int argc;
char *argv[];
{
    int len_string[MAX_INSTANCES][3];
    int block_string[MAX_INSTANCES][3];
    int numrec,j,num_except;
    FILE *fin,*file_exact,*file_apx,*fout,*fout2;
		int max_run,size_alphabet, type_run, shortest;
    char str[MAXLEN];
    int shortorlong, num_inst,num_seq,min_length,max_length;
		float ratio, sq_ratio, variance, similarity;
		char distrib[250], tempstr[MAXLEN];		
		float actual_ratio;
		
		if (argc<6)
				{
						printf("Arguments:\n");
						printf("file of instances\n"); 
						printf("file of  exact solutions\n");  
						printf("file of approximate solutions\n"); 
						printf("file of  Statistics\n"); 
						printf("file of Results\n"); 
						exit(5);
				}
		
		if ((fin=fopen(argv[1],"r"))==NULL)
				{
						printf("File <%s> : access denied\n",argv[1]);
						exit(5);
				}
		
		fscanf(fin,"%40c%d\n",&tempstr,&num_inst);
		fscanf(fin,"%40c%d\n",&tempstr,&num_seq);
		fscanf(fin,"%40c%d\n",&tempstr,&max_length);
		fscanf(fin,"%40c%d\n",&tempstr,&min_length);
		fscanf(fin,"%40c%d\n",&tempstr,&max_run);
		fscanf(fin,"%40c%d\n",&tempstr,&size_alphabet);
		fscanf(fin,"%40c%s\n",&tempstr,&distrib);
		fscanf(fin,"%40c%d\n",&tempstr,&type_run);
		
		
		
		if   (num_seq <= MAXSEQ_PD && max_length <= MAXLENGTH_PD) 
				shortorlong= SHORT;
		else
				shortorlong= LONG;
		
		if (shortorlong == SHORT)
				if ((file_exact=fopen(argv[2],"r"))==NULL)
						{
								printf("File <%s> : access denied\n",argv[2]);
								(void)			  fclose(fin);
								exit(EXIT_FAILURE);
						}
		if ((fout2=fopen(argv[4],"w"))==NULL)
				{
						printf("File <%s> : access denied\n",argv[4]);
						(void)	  fclose(fin);
						(void)	  fclose(file_exact);
						exit(EXIT_FAILURE);
				}  
		
		if ((file_apx=fopen(argv[3],"r"))==NULL)
				{
						printf("File <%s> : access denied\n",argv[3]);
						(void)	  fclose(fin);
						(void)	  fclose(fout);	
						(void)	  fclose(fout2);
						exit(EXIT_FAILURE);
				}
		
		if ((fout=fopen(argv[5],"w"))==NULL)
				{
						printf("File <%s> : access denied\n",argv[5]);
						(void)	  fclose(fin);
						(void)	  fclose(file_exact);
						(void)	  fclose(file_apx);
						(void)	  fclose(fout);
						exit(EXIT_FAILURE);
				}  
		
		/*------------------------------------------
			At the beginning of the file of Instances we van find
			some details about the generated instances
			------------------------------------------------*/
		get_alphabet(distrib,size_alphabet);     
		
		fprintf(fout2,"File Riepilogo\n");
		fprintf(fout2,"number of  instances                   : %d\n",num_inst);
		fprintf(fout2,"number of sequences in each instance   : %d\n", num_seq);
		fprintf(fout2,"max length of a sequence               : %d\n",max_length);
		fprintf(fout2,"min length of a sequence               : %d\n",min_length);
		fprintf(fout2,"maximum run                            : %d\n",max_run);
		fprintf(fout2,"size of the alphabet                   : %d\n",size_alphabet);
		fprintf(fout2,"filename of the distribution of symbols: %s\n",distrib); //wrong
		fprintf(fout2,"distribution of the run                : %d\n",type_run);
		
		fprintf(fout,"         Length                   ");
		if (shortorlong == SHORT)
				fprintf(fout,"                        Blocks");
		fprintf(fout,"\n");
		fprintf(fout,"  Exact    Approximate    ");
		if (shortorlong == SHORT)
				fprintf(fout,"  Exact    Approximate    ");
		fprintf(fout, "\n");
		
		//		printf("number of  instances: %d\n",num_inst);
		
		
		for(numrec=1 ; numrec<=num_inst; numrec++) 
				{
						for (j=0, shortest = MAXLEN  ; j< num_seq ;j++)
								{					
										if (fgets(str,MAXLEN,fin)==NULL)
												{
														printf("Error in file %s\n",argv[1]);
														goto fine;
												}
										
										if (Truelen(str)< shortest)
												shortest = Truelen(str);
										//										printf(" %5d ", Truelen(str));
								}
						//						printf("Shortest = %5d\n", shortest);
						if (shortorlong == SHORT)
								{
										if (fgets(str,MAXLEN,file_exact)==NULL)
												{
														printf("Error in file %s\n",argv[2]);
														goto fine;
												}
										len_string[numrec][0]=Truelen(str);
										block_string[numrec][0]=num_blocks(str);
										if (strcmp(str,"*")==0)
												{
														len_string[numrec][0]=0;
														block_string[numrec][0]=0;
												}
								}
						else
								len_string[numrec][0]=shortest;
						
						if (fgets(str,MAXLEN,file_apx)==NULL)
								{
										printf("Error in file %s\n",argv[3]);
										goto fine;
								}
						
						if (shortorlong == SHORT)
								block_string[numrec][1]=num_blocks(str);
						
						len_string[numrec][1]=Truelen(str);
					
								
						
				}
		
		
		for (numrec=1 ; numrec<= num_inst; numrec++)
				{
						fprintf(fout2, "  Instance n. %5d\n", numrec);
						fprintf(fout2,"Exact %6d\n", len_string[numrec][0]);
						fprintf(fout,"%5d", len_string[numrec][0]);
						if (shortorlong == SHORT)
								fprintf(fout,"%5d",block_string[numrec][0]);
						fprintf(fout2,"Expand %6d\n", len_string[numrec][1]);
						fprintf(fout,"%5d", len_string[numrec][1]);
						if (shortorlong == SHORT)
								fprintf(fout,"%5d",block_string[numrec][1]);
						fprintf(fout, "\n");
				}
		
		fprintf(fout2,"\n\n Results\n");	
		
		ratio=0;
		sq_ratio=0;
		similarity=0 ;
		
		
		for(numrec=1 ; numrec<=num_inst; numrec++) 
				{
						if (len_string[numrec][0]==0)
								{
										actual_ratio = 0;
										similarity=0;
										num_except++;
								}
						else
								actual_ratio = ((float) len_string[numrec][0]/(float)
																len_string[numrec][1]);
						
						ratio+= actual_ratio;
						sq_ratio+=pow(actual_ratio,2);
						if (shortorlong == SHORT && len_string[numrec][0] > 0 )
								similarity+=pow((float)
																((block_string[numrec][0]-block_string[numrec][1]) / block_string[numrec][0]),2);  
				}
		
		
		ratio=ratio/(num_inst-num_except);
		/* average ratio */
		variance=(sq_ratio /(num_inst-num_except)) - pow(ratio,2); 
		/* Var(X) = E[X^2] - (E[X})^2 */
		
		fprintf(fout2,"Expand\n" );		
		
		fprintf(fout2,"Average Ratio: %8f\n", ratio);
		fprintf(fout2,"Std. Dev. : %8f\n", sqrt(variance));  
		if (shortorlong == SHORT)
				fprintf(fout2,"Similarity: %8f\n", sqrt(similarity)); 
		
		
		
		
		
 fine:
		(void)  fclose(fin);
		if (shortorlong == SHORT)
				(void) 		fclose(file_exact);
		(void)   fclose(file_apx);
		(void)   fclose(fout);
		(void)   fclose(fout2);
		return(0);
}
